// Shared stat definitions (keys = percentiles from the server).
// desc = short explanation of "what is this and how is it computed" (tooltip on the ladder etc.)
// math = precise technical definition (thresholds, denominators, aggregation) — for the "technical" view on the ladder
export const STAT_DEFS = [
  { key: 'goals', label: 'Goals / game', cat: 'Attack', dec: 1, get: (p) => p.perGame.goals,
    desc: 'Goals scored, straight from the scoreboard.',
    math: 'x = scoreboard goals per player-game · ladder: mean_b = (1/n_b)·Σx over all player-games in bucket b' },
  { key: 'assists', label: 'Assists / game', cat: 'Attack', dec: 1, get: (p) => p.perGame.assists,
    desc: 'Scoreboard assists — the last pass before a teammate scored.',
    math: 'x = scoreboard assists per player-game · mean per bucket' },
  { key: 'shots', label: 'Shots / game', cat: 'Attack', dec: 1, get: (p) => p.perGame.shots,
    desc: 'Shots detected by the analyzer: touches that send the ball toward the goal fast enough (lower threshold near the net, so taps and rollers count).',
    math: 'shot := touch with post-touch ball velocity toward goal ≥ 500 uu/s (≥ 300 uu/s inside ~3000 uu of goal) · mean per bucket' },
  { key: 'shootingPct', label: 'Shooting %', cat: 'Attack', dec: 1, suffix: '%', get: (p) => p.perGame.shootingPct,
    desc: 'Goals ÷ shots. On the ladder this is total goals over total shots for the whole rank, so games without a shot don\'t drag it down.',
    math: 'ladder line: ratio of means = Σgoals_b / Σshots_b (NOT mean of per-game ratios) · whiskers: per-game G/S, games with S>0 only · "you": career Σg/Σs' },
  { key: 'xg', label: 'xG / game', cat: 'Attack', dec: 2, get: (p) => p.xg.xgPerGame,
    desc: 'Expected goals — each shot\'s chance of going in given distance, angle, speed and defender positions at the moment of the shot.',
    math: 'xG_shot = σ(a·logit(p_geo)+b), Platt-calibrated on real shot outcomes; p_geo from distance, angle, speed, open-goal factor (0.35–0.92), blocker on shot line (×0.62/×0.45); same-player sequences deduped, rebound ×1.3 pre-calibration · xG = Σ over shots' },
  { key: 'finishing', label: 'Finishing (G−xG)', cat: 'Attack', dec: 2, get: (p) => p.xg.finishingPerGame,
    desc: 'Goals minus expected goals. Positive = converting chances better than average; negative = leaving goals on the table.',
    math: 'finishing = goals − ΣxG per game · mean per bucket' },
  { key: 'score', label: 'Score / game', cat: 'Attack', dec: 0, get: (p) => p.perGame.score,
    desc: 'In-game score points (goals, saves, touches, demos…).',
    math: 'x = in-game score points per player-game · mean per bucket' },
  { key: 'saves', label: 'Saves / game', cat: 'Defense', dec: 1, get: (p) => p.perGame.saves,
    desc: 'Scoreboard saves.',
    math: 'x = scoreboard saves per player-game · mean per bucket' },
  { key: 'clears', label: 'Clears / game', cat: 'Defense', dec: 1, get: (p) => p.averages.clears,
    desc: 'Touches in your defensive third that send the ball toward the opponent\'s half.',
    math: 'clear := touch with ball in own third (|y| > y_field/3 on own side) AND post-touch velocity toward opponent half · count per game, mean per bucket' },
  { key: 'pressureClears', label: 'Clears under pressure', cat: 'Defense', dec: 1, get: (p) => p.averages.pressureClears,
    desc: 'Clears made with at least one opponent inside your defensive third.',
    math: 'subset of clears where ≥1 opponent position is inside your defensive third at touch time' },
  { key: 'pctBehindBall', label: 'Time behind ball', cat: 'Defense', dec: 1, suffix: '%', get: (p) => p.averages.pctBehindBall,
    desc: 'Share of time positioned between the ball and your own goal.',
    math: 'pct = 100 · t(own_goal_side_of_ball) / t_active, sampled every replay frame (~30 Hz)' },
  { key: 'concededAsLastMan', label: 'Conceded as last man', cat: 'Defense', dec: 1, invert: true, get: (p) => p.averages.concededAsLastMan,
    desc: 'Goals conceded while you were the deepest defender — the one who should have stopped it.',
    math: 'count of conceded goals where my y-position was deepest (closest to own goal) among my team at goal frame' },
  { key: 'concededWhileAhead', label: 'Caught upfield (goal)', cat: 'Defense', dec: 1, invert: true, get: (p) => p.averages.concededWhileAhead,
    desc: 'Goals conceded while you were caught in the attacking half.',
    math: 'count of conceded goals with my position in the attacking half at goal frame' },
  { key: 'demosTaken', label: 'Demos taken', cat: 'Defense', dec: 1, invert: true, get: (p) => p.totals.demosTaken / Math.max(1, p.games),
    desc: 'Times you got demolished.',
    math: 'demolition events (replay DemolishFx) where I am the victim · count per game' },
  { key: 'abandoned2v1', label: 'Left teammate in 2v1', cat: 'Rotation', dec: 1, invert: true, teamOnly: true, get: (p) => p.averages.abandoned2v1,
    desc: 'Opponent touched the ball deep in your defense while you were still far upfield — teammate left to defend alone.',
    math: 'events: opponent touch in our defensive third while my y > midfield · count per game' },
  { key: 'doubleCommits', label: 'Double commits', cat: 'Rotation', dec: 1, invert: true, teamOnly: true, get: (p) => p.averages.doubleCommits,
    desc: 'You and a teammate challenging the same ball at the same time.',
    math: 'events: me and a teammate both within challenge radius of ball (~850 uu) moving toward it in the same 0.9 s window' },
  { key: 'aheadStreakAvg', label: 'Time ahead of ball (s)', cat: 'Rotation', dec: 1, invert: true, get: (p) => p.averages.aheadStreakAvg,
    desc: 'Average length of a spell spent ahead of the ball. Long spells = slow rotation back into position.',
    math: 'mean duration of contiguous intervals with position on the attacking side of the ball' },
  { key: 'pctLostForward', label: 'Stranded upfield', cat: 'Rotation', dec: 1, suffix: '%', invert: true, get: (p) => p.averages.pctLostForward,
    desc: 'Share of time stranded in the attacking half while the ball is deep in your defensive third.',
    math: 'pct = 100 · t(me in attacking half ∧ ball in defensive half) / t_active' },
  { key: 'turnovers', label: 'Turnovers', cat: 'Rotation', dec: 1, invert: true, get: (p) => p.averages.turnovers,
    desc: 'Times you gave the ball away — an opponent\'s touch directly followed yours.',
    math: 'count of touch sequences (mine → opponent\'s) with no teammate touch between · per game' },
  { key: 'steals', label: 'Takeaways', cat: 'Rotation', dec: 1, get: (p) => p.averages.steals,
    desc: 'Times you took the ball off an opponent — your touch directly followed theirs.',
    math: 'count of touch sequences (opponent\'s → mine) · per game' },
  { key: 'possessionPct', label: 'Possession', cat: 'Possession & duels', dec: 1, suffix: '%', get: (p) => p.averages.possessionPct,
    desc: 'Share of match time the ball was last touched by you (your team\'s possession is split between its players).',
    math: 'pct = 100 · t(ball last touched by me) / t_active — per-player split of team possession' },
  { key: 'touchesPerMin', label: 'Touches / min', cat: 'Possession & duels', dec: 1, get: (p) => p.averages.touchesPerMin,
    desc: 'Ball touches per minute.',
    math: 'touches / (t_active/60); t_active excludes goal replays and kickoff countdowns' },
  { key: 'fiftyWinPct', label: '50/50s won', cat: 'Possession & duels', dec: 0, suffix: '%', get: (p) => p.averages.fiftyWinPct ?? 0,
    desc: '50/50 duels won — quick alternating touches with an opponent; whoever gets the last touch wins the exchange. League average is ~50% by definition, so what matters is your distance from 50.',
    math: '50/50 := alternating my/opponent touches within a short window; winner = last touch · pct = W/(W+L) · symmetric: both participants scored → league mean ≈ 50%' },
  { key: 'kickoffWinPct', label: 'Kickoff win %', cat: 'Possession & duels', dec: 0, suffix: '%', get: (p) => p.averages.kickoffWinPct ?? 0,
    desc: 'Kickoff won = ball in the opponent\'s half (or your team scores) within 3 s of the first touch. Both kickoff takers are scored, so the league average is ~50% by definition.',
    math: 'won := ball in opponent half (or our goal) 3 s after first touch · scored for first-touch player AND nearest opponent (symmetric since v13) · pct = W/(W+L)' },
  { key: 'aerialTouches', label: 'Aerial touches / game', cat: 'Possession & duels', dec: 1, get: (p) => p.averages.aerialTouches,
    desc: 'Touches above ~500 uu — from just below crossbar height (642 uu) and higher.',
    math: 'touches with ball z > 500 uu at contact · count per game' },
  { key: 'demos', label: 'Demos / game', cat: 'Possession & duels', dec: 1, get: (p) => p.perGame.demos,
    desc: 'Opponents you demolished.',
    math: 'demolition events where I am the attacker · count per game' },
  { key: 'avgBoost', label: 'Average boost', cat: 'Boost', dec: 1, get: (p) => p.averages.avgBoost,
    desc: 'Average boost in the tank (0–100) across the match.',
    math: 'time-weighted mean of boost amount (0–100), sampled per frame' },
  { key: 'boostPerMin', label: 'Usage / min', cat: 'Boost', dec: 0, get: (p) => p.averages.boostPerMin,
    desc: 'Boost consumed per minute.',
    math: 'Σ boost consumed / (t_active/60) — collected boost does not enter the numerator' },
  { key: 'pctZeroBoost', label: 'Time at 0 boost', cat: 'Boost', dec: 1, suffix: '%', invert: true, get: (p) => p.averages.pctZeroBoost,
    desc: 'Share of time sitting on empty — usually a boost-management leak.',
    math: 'pct = 100 · t(boost = 0) / t_active' },
  { key: 'bigPadsStolen', label: 'Big pads stolen', cat: 'Boost', dec: 1, get: (p) => p.averages.stolenBigPads,
    desc: 'Big (100) boost pads collected in the opponent\'s half.',
    math: 'big-pad (100) pickups with pad position in opponent half · count per game' },
  { key: 'avgSpeed', label: 'Avg speed (uu/s)', cat: 'Movement', dec: 0, get: (p) => p.averages.avgSpeed,
    desc: 'Average car speed. For scale: max driving speed without boost is 1410, supersonic is 2200 uu/s.',
    math: 'time-weighted mean |v_car| over active play · reference: no-boost max 1410, supersonic 2200 uu/s' },
  { key: 'pctSupersonic', label: 'Supersonic', cat: 'Movement', dec: 1, suffix: '%', get: (p) => p.averages.pctSupersonic,
    desc: 'Share of active play time at supersonic speed (≥2200 uu/s).',
    math: 'pct = 100 · t(|v| ≥ 2200) / t_active — denominator is ACTIVE time (no goal replays/kickoff pauses), so values run higher than sites that divide by total match time' },
  { key: 'pctHighAir', label: 'High air', cat: 'Movement', dec: 1, suffix: '%', get: (p) => p.averages.pctHighAir,
    desc: 'Share of time high in the air (above ~840 uu) — aerial play territory.',
    math: 'pct = 100 · t(car z > 840 uu) / t_active' },
  { key: 'powerslides', label: 'Powerslides / game', cat: 'Movement', dec: 1, get: (p) => p.averages.powerslides ?? 0,
    desc: 'Powerslide activations while on the ground (mid-air wavedash prep doesn\'t count).',
    math: 'count of rising edges of bReplicatedHandbrake while wheels on ground (airborne presses excluded) · per game' },
  { key: 'powerslidesPerMin', label: 'Powerslide freq / min', cat: 'Movement', dec: 1, get: (p) => p.averages.powerslidesPerMin ?? 0,
    desc: 'How often the powerslide button is pressed per minute of active play — slide frequency independent of match length. High values usually mean tighter turns and better landings.',
    math: 'powerslides / (t_active/60)' },
  { key: 'flipResets', label: 'Flip resets / game', cat: 'Movement', dec: 1, get: (p) => p.averages.flipResets ?? 0,
    desc: 'Heuristic detection: a ball touch with the wheels side of the car while high in the air (car above ~250 uu, ball above ~400 uu) — the classic flip-reset contact. Rare below Champion.',
    math: 'touch with car z > 250 ∧ ball z > 400 ∧ dot(car_up, dir_to_ball) < −0.55 (wheels-first contact; car_up from replicated quaternion) · count per game' },
];

export const statLabel = (key) => STAT_DEFS.find((d) => d.key === key)?.label || key;

/** Strengths/weaknesses from percentiles: top ≥70 and bottom ≤30. */
export function strengthsWeaknesses(percentiles, teamMode = true) {
  if (!percentiles) return { strengths: [], weaknesses: [] };
  const entries = STAT_DEFS
    .filter((d) => (!d.teamOnly || teamMode) && percentiles[d.key] != null)
    .map((d) => ({ ...d, pct: percentiles[d.key] }));
  const strengths = entries.filter((e) => e.pct >= 70).sort((a, b) => b.pct - a.pct).slice(0, 6);
  const weaknesses = entries.filter((e) => e.pct <= 30).sort((a, b) => a.pct - b.pct).slice(0, 6);
  return { strengths, weaknesses };
}
